# Generated by Django 5.2 on 2025-04-07 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('content', models.TextField()),
                ('exam_code', models.CharField(max_length=10, unique=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.class')),
                ('exam_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL)),
                ('stream_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.stream')),
            ],
        ),
    ]
