# Generated by Django 5.2 on 2025-04-08 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cat_cat_date_examination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_results', to='api.cat')),
                ('cat_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_results', to='api.student')),
                ('cat_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_results', to='api.subject')),
                ('cat_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
