# Generated by Django 5.2 on 2025-04-08 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_catgrading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catgrading',
            old_name='is_busines_studies',
            new_name='is_business_studies',
        ),
        migrations.CreateModel(
            name='ExamGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_marks', models.IntegerField()),
                ('exam_grade', models.CharField(max_length=10)),
                ('is_english', models.BooleanField(default=False)),
                ('is_maths', models.BooleanField(default=False)),
                ('is_kiswahili', models.BooleanField(default=False)),
                ('is_chemistry', models.BooleanField(default=False)),
                ('is_physics', models.BooleanField(default=False)),
                ('is_biology', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
                ('is_geography', models.BooleanField(default=False)),
                ('is_cre', models.BooleanField(default=False)),
                ('is_business_studies', models.BooleanField(default=False)),
                ('is_agriculture', models.BooleanField(default=False)),
                ('is_computer_studies', models.BooleanField(default=False)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grading', to='api.exams')),
                ('exam_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grade', to='api.student')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grading', to='api.subject')),
                ('exam_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
