# Generated by Django 5.2 on 2025-04-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_is_busines_studies_catgrading_is_business_studies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAndExamGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.CharField(max_length=10)),
                ('cat_grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.catgrading')),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam_grading', to='api.cat')),
                ('exam_grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examgrading')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam_grading', to='api.exams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam_grading', to='api.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam_grading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
