# Generated by Django 5.2 on 2025-04-09 13:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_catandexamgrading_cat_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=2400))),
                ('date_done', models.DateField()),
                ('start_time', models.TimeField()),
                ('cat_code', models.CharField(max_length=20, unique=True)),
                ('end_time', models.TimeField()),
                ('is_english', models.BooleanField(default=False)),
                ('is_maths', models.BooleanField(default=False)),
                ('is_kiswahili', models.BooleanField(default=False)),
                ('is_chemistry', models.BooleanField(default=False)),
                ('is_physics', models.BooleanField(default=False)),
                ('is_biology', models.BooleanField(default=False)),
                ('is_geography', models.BooleanField(default=False)),
                ('is_cre', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
                ('is_computer_studies', models.BooleanField(default=False)),
                ('is_business_studies', models.BooleanField(default=False)),
                ('is_agriculture', models.BooleanField(default=False)),
                ('cat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='api.class')),
                ('cat_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='api.stream')),
                ('cat_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CatGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(max_length=3)),
                ('grade', models.CharField(max_length=10)),
                ('date_graded', models.DateTimeField(auto_now_add=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_maths', models.BooleanField(default=False)),
                ('is_kiswahili', models.BooleanField(default=False)),
                ('is_chemistry', models.BooleanField(default=False)),
                ('is_physics', models.BooleanField(default=False)),
                ('is_biology', models.BooleanField(default=False)),
                ('is_geography', models.BooleanField(default=False)),
                ('is_cre', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
                ('is_computer_studies', models.BooleanField(default=False)),
                ('is_business_studies', models.BooleanField(default=False)),
                ('is_agriculture', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_grading', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_grading', to='api.subject')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_grading', to=settings.AUTH_USER_MODEL)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_grading', to='api.cats')),
            ],
        ),
    ]
