# Generated by Django 5.2 on 2025-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cats_catgrading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgrading',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
