# Generated by Django 5.2 on 2025-04-10 01:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_stream_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('date_done', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_code', models.CharField(max_length=20, unique=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_maths', models.BooleanField(default=False)),
                ('is_kiswahili', models.BooleanField(default=False)),
                ('is_chemistry', models.BooleanField(default=False)),
                ('is_physics', models.BooleanField(default=False)),
                ('is_biology', models.BooleanField(default=False)),
                ('is_geography', models.BooleanField(default=False)),
                ('is_cre', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
                ('is_computer_studies', models.BooleanField(default=False)),
                ('is_business_studies', models.BooleanField(default=False)),
                ('is_agriculture', models.BooleanField(default=False)),
                ('exam_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.class')),
                ('exam_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.stream')),
                ('exam_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('date_graded', models.DateTimeField(auto_now_add=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_maths', models.BooleanField(default=False)),
                ('is_kiswahili', models.BooleanField(default=False)),
                ('is_chemistry', models.BooleanField(default=False)),
                ('is_physics', models.BooleanField(default=False)),
                ('is_biology', models.BooleanField(default=False)),
                ('is_geography', models.BooleanField(default=False)),
                ('is_cre', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
                ('is_computer_studies', models.BooleanField(default=False)),
                ('is_business_studies', models.BooleanField(default=False)),
                ('is_agriculture', models.BooleanField(default=False)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grading', to='api.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grading', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grading', to='api.subject')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
