# Generated by Django 5.2 on 2025-04-10 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_exam_examgrading'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAndExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam', to='api.class')),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam', to='api.student')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam', to=settings.AUTH_USER_MODEL)),
                ('stream_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam', to='api.stream')),
                ('student_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam', to='api.catgrading')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam', to='api.examgrading')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam', to='api.subject')),
            ],
        ),
    ]
