# Generated by Django 5.2 on 2025-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_catandexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catandexam',
            name='student_cat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='catandexam',
            name='student_exam',
            field=models.IntegerField(),
        ),
    ]
