# Generated by Django 5.2 on 2025-04-11 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_streamclasssubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAndExamGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField()),
                ('student_subject', models.CharField(max_length=100, unique=True)),
                ('subject_cat_marks', models.IntegerField()),
                ('subject_exam_marks', models.IntegerField()),
                ('student_class', models.CharField(max_length=10)),
                ('student_stream', models.CharField(max_length=10)),
                ('subject_total', models.IntegerField()),
                ('subject_grade', models.CharField(max_length=10)),
                ('is_english_cat', models.BooleanField(default=0)),
                ('is_english_exam', models.BooleanField(default=0)),
                ('is_english_total', models.BooleanField(default=0)),
                ('is_english_grade', models.BooleanField(default=0)),
                ('is_maths_cat', models.BooleanField(default=0)),
                ('is_maths_exam', models.BooleanField(default=0)),
                ('is_maths_total', models.BooleanField(default=0)),
                ('is_maths_grade', models.BooleanField(default=0)),
                ('is_kiswahili_cat', models.BooleanField(default=0)),
                ('is_kiswahili_exam', models.BooleanField(default=0)),
                ('is_kiswahili_total', models.BooleanField(default=0)),
                ('is_kiswahili_grade', models.BooleanField(default=0)),
                ('is_physics_cat', models.BooleanField(default=0)),
                ('is_physics_exam', models.BooleanField(default=0)),
                ('is_physics_total', models.BooleanField(default=0)),
                ('is_physics_grade', models.BooleanField(default=0)),
                ('is_chemistry_cat', models.BooleanField(default=0)),
                ('is_chemistry_exam', models.BooleanField(default=0)),
                ('is_chemistry_total', models.BooleanField(default=0)),
                ('is_chemistry_grade', models.BooleanField(default=0)),
                ('is_biology_cat', models.BooleanField(default=0)),
                ('is_biology_exam', models.BooleanField(default=0)),
                ('is_biology_total', models.BooleanField(default=0)),
                ('is_biology_grade', models.BooleanField(default=0)),
                ('is_geography_cat', models.BooleanField(default=0)),
                ('is_geography_exam', models.BooleanField(default=0)),
                ('is_geography_total', models.BooleanField(default=0)),
                ('is_geography_grade', models.BooleanField(default=0)),
                ('is_cre_cat', models.BooleanField(default=0)),
                ('is_cre_exam', models.BooleanField(default=0)),
                ('is_cre_total', models.BooleanField(default=0)),
                ('is_cre_grade', models.BooleanField(default=0)),
                ('is_history_cat', models.BooleanField(default=0)),
                ('is_history_exam', models.BooleanField(default=0)),
                ('is_history_total', models.BooleanField(default=0)),
                ('is_history_grade', models.BooleanField(default=0)),
                ('is_agriculture_cat', models.BooleanField(default=0)),
                ('is_agriculture_exam', models.BooleanField(default=0)),
                ('is_agriculture_total', models.BooleanField(default=0)),
                ('is_agriculture_grade', models.BooleanField(default=0)),
                ('is_computer_studies_cat', models.BooleanField(default=0)),
                ('is_computer_studies_exam', models.BooleanField(default=0)),
                ('is_computer_studies_total', models.BooleanField(default=0)),
                ('is_computer_studies_grade', models.BooleanField(default=0)),
                ('is_business_studies_cat', models.BooleanField(default=0)),
                ('is_business_studies_exam', models.BooleanField(default=0)),
                ('is_business_studies_total', models.BooleanField(default=0)),
                ('is_business_studies_grade', models.BooleanField(default=0)),
                ('student_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_and_exam_grading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
