# Generated by Django 5.2 on 2025-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_catandexamgrading_is_agriculture_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_agriculture_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_biology_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_business_studies_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_chemistry_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_computer_studies_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_cre_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_english_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_geography_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_history_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_kiswahili_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_maths_grade',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='catandexamgrading',
            name='is_physics_grade',
            field=models.CharField(default=0),
        ),
    ]
