# Generated by Django 5.2 on 2025-04-16 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_catandexamgrading_is_agriculture_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=10)),
                ('total_subjects', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('final_grade', models.CharField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
