# Generated by Django 5.2 on 2025-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_finalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catandexamgrading',
            name='student_subject',
            field=models.CharField(max_length=100),
        ),
    ]
