# Generated by Django 5.2 on 2025-04-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_reportform_term_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_term',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
