# Generated by Django 5.2 on 2025-04-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_exam_exam_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_code',
            field=models.CharField(max_length=100),
        ),
    ]
